### PR TITLE
feat/websockets-ssl

### PR DESCRIPTION
**Pull request by radim-kliment**
## Description:
Added support for websocket transport layer and activation of ssl.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/theengs/gateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by koenvervloesem** [comment]
Thanks for these useful features!

Can you:

- [Run pre-commit](https://gateway.theengs.io/participate/development.html#development-contributions) and fix the found issues.
- Rename all parameters that have `ssl` in their name to use `tls` because everyone should use TLS these days.

**Comment by radim-kliment** [comment]
I fix errors from lint, but I get this error, which is line of code I did not edit:

`TheengsGateway/diagnose.py:108: error: Module has no attribute "freedesktop_os_release"  [attr-defined]`

**Comment by koenvervloesem** [comment]
You're probably running this on a Python version lower than 3.10? Don't worry about it then.

**Comment by radim-kliment** [comment]
yep, Iam running this on python 3.9

**Comment by koenvervloesem** [comment]
The `diagnose` module should run fine because the code checks whether the Python version >= 3.10 before calling `freedesktop_os_release()`, but apparently the linter doesn't know this.

Anyway, thanks again for your contribution! This is a nice addition for the upcoming release.

**Comment by 1technophile** [comment]
Hello,
Thanks!
Maybe the options should be added into the docs?
https://github.com/theengs/gateway/blob/development/docs/use/use.md

**Comment by koenvervloesem** [comment]
I documented the options in https://github.com/theengs/gateway/pull/161 and changed the types to `int` for consistency with the other options.

**Pull request merged**
